# Generated by Django 6.1.1 on 2026-10-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_reviewed_at_article_reviewed_by_approvallog'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='publishers.publisher'),
        ),
    ]
