# Generated by Django 6.1.1 on 2026-10-01 15:13

from django.db import migrations, models

def copy_group_to_role(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    role_priority = [
        "Administrator",
        "Publisher Manager",
        "Editor",
        "Journalist",
        "Reader",
    ]

    for user in User.objects.all():
        group_names = set(
            user.groups.values_list("name", flat=True)
        )

        matching_role = next(
            (
                role
                for role in role_priority
                if role in group_names
            ),
            "Reader",
        )

        user.role = matching_role
        user.save(update_fields=["role"])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_publishers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Journalist', 'Journalist'), ('Editor', 'Editor'), ('Publisher Manager', 'Publisher Manager'), ('Administrator', 'Administrator')], default='Reader', max_length=30),
        ),
        migrations.RunPython(
            copy_group_to_role,
            migrations.RunPython.noop,
        ),
    ]
